### ISSUE TITLE
docker環境作成

### ISSUE THREAD

**Issue by masayomitan** [masayomitan/oshierukun#4]
docekr上でお互いの環境を一緒にする

**Comment by masayomitan** [comment]
詰まってます笑
今週待って欲しいです

**Comment by masayomitan** [comment]
docker 環境は作れたましたが、今これでちゃんとできているか確認中
土曜日には上がりまする

**Comment by masayomitan** [comment]
色々　gitやらかしました。汗
現状では devlopのソースコードで
コンテナー立ち上げてから
docker exec -it oshierukun_app_1 php artisan serve --host 0.0.0.0 
でローカルみれます。

**Comment by kakeisbs** [comment]
いえー、ありがとうございますー。pullっておきますね。
